//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace loginpage {
	
	
	public partial class Default {
		
		protected System.Web.UI.WebControls.Content Content1;
		
		protected System.Web.UI.HtmlControls.HtmlForm form1;
		
		protected System.Web.UI.WebControls.Label Label1;
		
		protected System.Web.UI.WebControls.TextBox login;
		
		protected System.Web.UI.WebControls.RadioButton RadioButton1;
		
		protected System.Web.UI.WebControls.RadioButton RadioButton2;
		
		protected System.Web.UI.WebControls.HyperLink a1;
		
		protected System.Web.UI.WebControls.HyperLink a2;
		
		protected System.Web.UI.WebControls.HyperLink hyp1;
		
		protected System.Web.UI.WebControls.Panel Panel1;
		
		protected System.Web.UI.WebControls.Label Label5;
		
		protected System.Web.UI.WebControls.TextBox TextBox5;
		
		protected System.Web.UI.WebControls.Label Label6;
		
		protected System.Web.UI.WebControls.TextBox TextBox6;
		
		protected System.Web.UI.WebControls.Label Label7;
		
		protected System.Web.UI.WebControls.TextBox TextBox7;
		
		protected System.Web.UI.WebControls.RequiredFieldValidator RequiredFieldValidator3;
		
		protected System.Web.UI.WebControls.CompareValidator CompareValidator1;
		
		protected System.Web.UI.WebControls.Button button1;
		
		protected System.Web.UI.WebControls.HiddenField hfield1;
		
		protected System.Web.UI.WebControls.ValidationSummary ValidationSummary1;
		
		protected System.Web.UI.WebControls.Label genderId;
	}
}
