//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace loginpage {
	
	
	public partial class login2 {
		
		protected System.Web.UI.WebControls.Content Content1;
		
		protected System.Web.UI.HtmlControls.HtmlForm form1;
		
		protected System.Web.UI.WebControls.TextBox TextBox1;
		
		protected System.Web.UI.WebControls.RequiredFieldValidator RequiredFieldValidator1;
		
		protected System.Web.UI.WebControls.TextBox TextBox2;
		
		protected System.Web.UI.WebControls.RequiredFieldValidator RequiredFieldValidator2;
		
		protected System.Web.UI.WebControls.TextBox TextBox3;
		
		protected System.Web.UI.WebControls.RequiredFieldValidator RequiredFieldValidator3;
		
		protected System.Web.UI.WebControls.TextBox TextBox4;
		
		protected System.Web.UI.WebControls.RequiredFieldValidator RequiredFieldValidator4;
		
		protected System.Web.UI.WebControls.TextBox TextBox5;
		
		protected System.Web.UI.WebControls.RequiredFieldValidator RequiredFieldValidator5;
		
		protected System.Web.UI.WebControls.Button Button3;
		
		protected System.Web.UI.WebControls.Button Button5;
		
		protected System.Web.UI.WebControls.Button Button4;
		
		protected System.Web.UI.WebControls.Label Label2;
		
		protected System.Web.UI.WebControls.Label login2label1;
		
		protected System.Web.UI.WebControls.Label msglabel;
		
		protected System.Web.UI.WebControls.GridView GridView1;
	}
}
